#Can Add User Data
#user_data: {default: '', description: User data script to be executed by cloud-init.,
#  immutable: false, required: false, type: string, update_allowed: false}



# Juno Release
heat_template_version: 2014-10-16


description: >
  Simply installs a basic Ubuntu server. But one that is set to replace the instance if the stack is udpated.


parameters:

  key_name:
    type: string
    label: Key Name
    description: Name of an existing KeyPair to enable SSH access to the instances. 
    constraints:
      - custom_constraint: nova.keypair
        description: Must be an existing keypair

  image_name:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: Ubuntu 14.04
    constraints:
        - allowed_values: [ Ubuntu 14.04, Ubuntu 15.04 ]
          description: Value must be one of Ubuntu 14.04, Ubuntu 15.04 .
    
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used. 
    default: m2.small
    constraints:
        - allowed_values: [m2.small, m1.small, m1.medium, m1.large, m1.xlarge ]
          description: Value must be one of m1.small, m1.medium, m1.large or m1.xlarge.

resources:

  basic_server:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key_name }
            image: 
              Fn::Select:
                - { get_param: image_name }
                -
                  'Ubuntu 14.04': 2a882d9c-3185-414c-9683-a4646b5c785e
                  'Ubuntu 15.04': fc48b5bb-e67d-4e39-b9ba-b6725c8b0c88
            flavor: { get_param: instance_type }
            image_update_policy: REPLACE
            user_data_format: RAW
            # YOU CAN ADD USER DATA HERE! EG 
                #user_data: {default: '', description: User data script to be executed by cloud-init.,
                #immutable: false, required: false, type: string, update_allowed: false}


    
outputs:
    instance_ip:
        description: The IP address of the deployed instance.
        value: { get_attr: [basic_server, first_address] }
